services:
  web:
    build: .
    container_name: flask-file-transfer
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:////app/data/app.db
      - GOOGLE_APPLICATION_CREDENTIALS=/app/data/creds.json
      - DATABASE_TYPE=GCS
    restart: unless-stopped